Permit unlimited restarts for pomo.service
This prevents pomo.service from crashing due to bad error handling:

    error: Uncaught (in promise) TypeError: error sending request for url (...): error trying to connect: dns error: failed to lookup address information: Name or service not known
         at async mainFetch (deno:ext/fetch/26_fetch.js:247:14)
         at async fetch (deno:ext/fetch/26_fetch.js:464:9)
         at async file:///nix/store/w2l8fdplkjbjxi8i9yryh00wr2xwjgph-pomo-src/server/main.ts:11:26